typedef enum Errors {
    VARIABLE_INEXISTENTE,
    ERROR_DE_SINTAXIS,
    ERROR_LEXICO,
    LONGITUD_MAXIMA_LEXEME,
    LONGITUD_MAXIMA_IDENTIFICADOR,
    LONGITUD_MAXIMA_CONSTANTE,
    DESBORDAMIENTO_DE_ENTERO
} Errors;

void showError(Errors numError);